---
- hosts: web
  remote_user: ansible_remote
  become_method: sudo
  become: yes

  tasks:
    - name: create folder
      file: path=/downloads state=directory

    - name: create test.yml
      file: path=/downloads/test.yml state=touch

    - name: copy playbook
      file: src=~/ansible_test_playbooks/web_build.yml dest=/downloads
