---
- hosts: web
  remote_user: ansible_remote
  become_method: sudo
  become: yes

  tasks:
    - name: install apache2 latest
      apt: pkg=apache2 state=latest
      when: ansible_os_family == 'Debian'

    - name: install php latest
      apt: pkg=php5 state=latest
      when: ansible_os_family == 'Debian'
      notify: restart_apache2

    - name: install httpd latest
      yum: pkg=httpd state=latest
      when: ansible_os_family == 'RedHat'

    - name: install php latest
      yum: pkg=php state=latest
      when: ansible_os_family == 'RedHat'
      notify: restart_httpd

  handlers:
    - name: restart_apache2
      service:
        name: apache2
        state: restarted
        enabled: yes

    - name: restart_httpd
      service:
        name: httpd
        state: restarted
        enabled: yes
